apiVersion: v1
kind: Service
metadata:
  name: elasticstack
  namespace: default
  labels:
    k8s-app: elasticstack
spec:
#  ExternalName: ""
  type: NodePort
  ports:
  - name: "http"
    nodePort: 32200
    port: 9200
  - name: "api"
    nodePort: 32300
    port: 9300
  - name: "kibana"
    nodePort: 32601
    port: 5601
  selector:
    k8s-app: elasticstack
status:
  loadBalancer: {}
