apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    k8s-app: elasticstack
  name: elasticstack
  namespace: default
spec:
  replicas: 1
  selector:
    k8s-app: elasticstack
  template:
    metadata:
      labels:
        k8s-app: elasticstack
    spec:
      containers:
      - image: elasticsearch:2.3.5
        imagePullPolicy: ""
        name: elasticsearch
        args:
        - -Des.cluster.name=k8s_cluster
        ports:
        - containerPort: 9200
          name: db
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        resources: {}
        volumeMounts:
        - name: es-persistent-storage
          mountPath: /usr/share/elasticsearch/data
      - image: kibana:4.5.4
        env:
          - name: ELASTICSEARCH_URL
            value: http://elasticstack:9200
        imagePullPolicy: ""
        name: kibana
        ports:
        - containerPort: 5601
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: es-persistent-storage
        emptyDir: {}
status:
  replicas: 0
